name: math_genius
description: An app to test your mathematical skills.
version: 1.0.0+1
author: Leonardo Vencovsky <leonardo.vencovsky@gmail.com>
homepage: https://github.com/LeoVen

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  path_provider: ^1.2.0

flutter:

  uses-material-design: true
